# Generated by Django 3.2.7 on 2021-09-28 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_assetsource_is_discontinued'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstate',
            name='last_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
