# Generated by Django 3.2.7 on 2021-09-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_appstate_last_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appstate',
            old_name='last_posted',
            new_name='last_run',
        ),
    ]
